name: GitDrops Run 

on:
  schedule:
    - cron: "0 7 * * *"       
  push:
    paths:
    - 'gitdrops.yaml'         
    branches: [ main ]

jobs:
  gitdrops-run:
    runs-on: ubuntu-latest
    env:
            DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    
    - name: Run GitDrops
      run: go run main.go
